version: 2

sources:
  - name: test
    database: airbnb
    schema: raw
    tables:
      - name: raw_hosts
      - name: raw_listings
      - name: raw_reviews
      - name: orders
      - name: Customers
      - name: ab

  - name: Exp
    database: MYDB
    schema: public
    tables:
      - name: em
        freshness:
          warn_after: { count: 1, period: minute }
          error_after: { count: 5, period: minute }
        loaded_at_field: dtime
      - name: dept
      - name: emp
      - name: salesdet

  - name: SLEEK
    database: SLEEKMART_OMS
    schema: TRAINING
    tables:
      - name: SALES_INDIA
      - name: SALES_UK
      - name: SALES_US
      - name: TRAVELLERS
      - name: TRIP_BOOKINGS
      
  - name: SLEEKL1
    database: SLEEKMART_OMS
    schema: L1_LANDING
    tables:
      - name: CUSTOMERS
      - name: DATES
      - name: EMPLOYEES
      - name: ORDERITEMS
      - name: ORDERS
      - name: PRODUCTS
      - name: STORES
      - name: SUPPLIERS
